In [1]:
%reset -f

In [1]:
import pymol
import os
import pandas as pd
import numpy as np
from tqdm import tqdm
from rdkit import Chem
from rdkit.Chem import AllChem

In [3]:
# 读取目录下的DrugMatrix.csv
df = pd.read_csv('DILI_drugs_oral.csv',encoding='GBK')
df.head()

,LTKBID,COMPOUND_NAME,NAME,Way,SeverityClass,LabelSection,vDILI-Concern,Comment,CID,IUPAC_Name,SMILES
0,LT00040,Abacavir sulfate,阿巴卡韦硫酸盐,口服,8,Warnings & precautions,vMOST-DILI-concern,Unchanged,441384,"bis([(1S,4R)-4-[2-amino-6-(cyclopropylamino)pu...",C1CC1NC2=C3C(=NC(=N2)N)N(C=N3)[C@@H]4C[C@@H](C...
1,LT03619,Abemaciclib,阿贝莫司他,口服,3,Warnings & precautions,vLess-DILI-concern,New,46220502,N-[5-[(4-ethylpiperazin-1-yl)methyl]-2-pyridin...,CCN1CCN(CC1)CC2=CN=C(C=C2)NC3=NC=C(C(=N3)C4=CC...
2,LT02339,Abiraterone acetate,阿比特龙醋酸盐,口服,8,Warnings & precautions,vMost-DILI-concern,New,9821849,"[(3S,8R,9S,10R,13S,14S)-10,13-dimethyl-17-pyri...",CC(=O)O[C@H]1CC[C@@]2([C@H]3CC[C@]4([C@H]([C@@...
3,LT03614,Acalabrutinib,阿卡布替尼,口服,4,Adverse reactions,Ambiguous-DILI-concern,New,71226662,4-[8-amino-3-[(2S)-1-but-2-ynoylpyrrolidin-2-y...,CC#CC(=O)N1CCC[C@H]1C2=NC(=C3N2C=CN=C3N)C4=CC=...
4,LT01141,Acamprosate calcium,阿坎酸钙,口服,3,Adverse reactions,vLess-DILI-concern,Unchanged,155434,calcium bis(3-acetamidopropane-1-sulfonate),CC(=O)NCCCS(=O)(=O)[O-].CC(=O)NCCCS(=O)(=O)[O-...

In [6]:
# 设置输出目录为当前文件夹
output_dir = os.getcwd()

# 从SMILES生成RDKit分子对象,SMILES为df['SMILES']
df['mol'] = df['SMILES'].apply(Chem.MolFromSmiles)
df['mol'] = df['mol'].apply(Chem.AddHs)
# 构象优化
# 保存为pdb文件，文件名为CID列的值
# for i in tqdm(range(df.shape[0])):
#     mol = df['mol'][i]
#     cid = df['CID'][i]
#     AllChem.EmbedMolecule(mol,useRandomCoords=True)
#     AllChem.MMFFOptimizeMolecule(mol)
#     Chem.MolToPDBFile(mol, os.path.join(output_dir, f'{cid}.pdb'))

# 修改上面for循环，出现错误或者提示信息时，跳过该分子，继续下一个分子
for i in tqdm(range(df.shape[0])):
    try:
        mol = df['mol'][i]
        cid = df['LTKBID'][i]
        print(f'{cid}.pdb')
        AllChem.EmbedMolecule(mol)
        AllChem.MMFFOptimizeMolecule(mol)
        Chem.MolToPDBFile(mol, os.path.join(output_dir, f'{cid}.pdb'))
    except:
        pass
df.head()

  0%|          | 1/961 [00:00<01:51,  8.61it/s]

LT00040.pdb
LT03619.pdb

  0%|          | 3/961 [00:00<02:06,  7.58it/s]

LT02339.pdb
LT03614.pdb

  0%|          | 4/961 [00:00<01:58,  8.08it/s][21:03:46] UFFTYPER: Unrecognized atom type: Ca+2 (0)

LT01141.pdb
LT01034.pdb

  1%|          | 12/961 [00:00<00:48, 19.45it/s]

LT01035.pdb
LT01853.pdb
LT00004.pdb
LT00498.pdb
LT00913.pdb
LT01041.pdb
LT01042.pdb
LT00041.pdb

  2%|▏         | 15/961 [00:01<00:54, 17.46it/s]

LT01155.pdb
LT02889.pdb

  2%|▏         | 18/961 [00:01<01:09, 13.65it/s]

LT02213.pdb
LT00461.pdb

  2%|▏         | 22/961 [00:01<00:55, 16.87it/s]

LT00499.pdb
LT01051.pdb
LT00692.pdb
LT03620.pdb
LT00980.pdb
LT01107.pdb
LT01244.pdb

  3%|▎         | 28/961 [00:02<01:29, 10.43it/s]

LT00043.pdb
LT01053.pdb
LT02888.pdb
LT01070.pdb
LT03621.pdb

  3%|▎         | 33/961 [00:02<01:05, 14.10it/s]

LT01060.pdb
LT00501.pdb
LT00502.pdb
LT01215.pdb
LT00503.pdb
LT01629.pdb

  4%|▍         | 38/961 [00:03<01:20, 11.52it/s]

LT00618.pdb
LT03376.pdb
LT03895.pdb
LT02070.pdb
LT00045.pdb

  4%|▍         | 43/961 [00:03<01:13, 12.42it/s]

LT01071.pdb
LT00711.pdb
LT00046.pdb

  5%|▍         | 45/961 [00:03<01:18, 11.61it/s]

LT01793.pdb
LT00047.pdb
LT00175.pdb

  5%|▌         | 50/961 [00:04<01:09, 13.09it/s]

LT02067.pdb
LT00256.pdb
LT00507.pdb
LT02100.pdb
LT00049.pdb

  5%|▌         | 52/961 [00:04<01:09, 13.17it/s]

LT01055.pdb

  6%|▌         | 56/961 [00:04<01:28, 10.25it/s]

LT00964.pdb
LT00263.pdb
LT03622.pdb
LT02418.pdb
LT00693.pdb

  6%|▌         | 59/961 [00:05<02:11,  6.83it/s]

LT03623.pdb
LT01195.pdb

  6%|▋         | 62/961 [00:05<01:51,  8.07it/s]

LT02077.pdb
LT01143.pdb
LT01230.pdb
LT01865.pdb

  7%|▋         | 64/961 [00:05<01:35,  9.38it/s]

LT03625.pdb
LT00053.pdb
LT01199.pdb

  7%|▋         | 67/961 [00:06<02:19,  6.39it/s]

LT00277.pdb
LT03626.pdb

  7%|▋         | 69/961 [00:06<02:18,  6.46it/s]

LT01139.pdb
LT00258.pdb

[21:03:52] UFFTYPER: Unrecognized atom type: Ca+2 (0)
  8%|▊         | 73/961 [00:07<02:22,  6.23it/s][21:03:53] UFFTYPER: Unrecognized charge state for atom: 11
[21:03:53] UFFTYPER: Unrecognized atom type: Au5+3 (0)

LT01096.pdb
LT00511.pdb
LT02166.pdb
LT03627.pdb

  8%|▊         | 76/961 [00:08<02:12,  6.67it/s]

LT02440.pdb
LT03628.pdb

  8%|▊         | 78/961 [00:08<02:29,  5.92it/s]

LT03629.pdb

  8%|▊         | 79/961 [00:08<02:14,  6.53it/s]

LT02399.pdb
LT00006.pdb
LT03630.pdb

  8%|▊         | 81/961 [00:08<01:46,  8.25it/s]

LT00265.pdb

  9%|▊         | 82/961 [00:09<03:54,  3.75it/s]

LT01113.pdb
LT03631.pdb

  9%|▉         | 86/961 [00:09<02:16,  6.43it/s]

LT00512.pdb
LT03632.pdb
LT02400.pdb

  9%|▉         | 88/961 [00:10<02:31,  5.77it/s]

LT03633.pdb

  9%|▉         | 90/961 [00:10<01:58,  7.35it/s]

LT03634.pdb
LT03635.pdb
LT01116.pdb

 10%|█         | 97/961 [00:10<00:56, 15.43it/s]

LT01117.pdb
LT00825.pdb
LT00513.pdb
LT01120.pdb
LT00278.pdb
LT01121.pdb
LT02756.pdb
LT00800.pdb

 11%|█         | 101/961 [00:11<01:08, 12.49it/s]

LT00832.pdb
LT01123.pdb
LT03636.pdb

 11%|█         | 106/961 [00:11<00:52, 16.23it/s]

LT02189.pdb
LT01132.pdb
LT00730.pdb
LT03798.pdb
LT01064.pdb

 12%|█▏        | 111/961 [00:11<00:48, 17.44it/s]

LT00056.pdb
LT03637.pdb
LT00817.pdb
LT02190.pdb
LT01136.pdb
LT01140.pdb

 12%|█▏        | 113/961 [00:11<01:13, 11.56it/s]

LT02349.pdb
LT03640.pdb

 12%|█▏        | 115/961 [00:12<01:30,  9.33it/s]

LT03641.pdb
LT03643.pdb

 12%|█▏        | 117/961 [00:12<01:34,  8.95it/s]

LT00519.pdb
LT00279.pdb

 13%|█▎        | 121/961 [00:13<01:49,  7.65it/s]

LT02076.pdb
LT01144.pdb

 13%|█▎        | 124/961 [00:13<01:20, 10.35it/s]

LT01145.pdb
LT00058.pdb
LT01148.pdb
LT00280.pdb
LT00707.pdb
LT01151.pdb

 13%|█▎        | 127/961 [00:13<01:08, 12.11it/s]

LT01152.pdb
LT02429.pdb

 13%|█▎        | 129/961 [00:13<01:30,  9.18it/s]

LT01888.pdb
LT00899.pdb

 14%|█▎        | 131/961 [00:14<01:37,  8.52it/s][21:03:59] UFFTYPER: Unrecognized atom type: Ca+2 (0)
 14%|█▍        | 133/961 [00:14<01:29,  9.20it/s]

LT00947.pdb
LT02899.pdb
LT01022.pdb

 14%|█▍        | 135/961 [00:14<01:50,  7.48it/s]

LT03645.pdb
LT02018.pdb
LT03646.pdb

 15%|█▍        | 140/961 [00:14<01:11, 11.51it/s]

LT00059.pdb
LT00060.pdb
LT01160.pdb
LT00759.pdb
LT00675.pdb
LT03647.pdb

 15%|█▌        | 145/961 [00:15<00:57, 14.11it/s]

LT02037.pdb
LT00207.pdb
LT01166.pdb

 15%|█▌        | 147/961 [00:15<01:08, 11.90it/s]

LT01167.pdb
LT01289.pdb
LT01087.pdb

 16%|█▌        | 149/961 [00:15<01:32,  8.74it/s]

LT01173.pdb
LT01180.pdb

 16%|█▌        | 153/961 [00:16<01:34,  8.57it/s]

LT01182.pdb
LT01183.pdb
LT00252.pdb

 16%|█▌        | 156/961 [00:16<01:15, 10.70it/s]

LT03650.pdb
LT01189.pdb
LT01279.pdb
LT03596.pdb

 16%|█▋        | 158/961 [00:16<01:22,  9.69it/s]

LT01190.pdb
LT01048.pdb
LT00065.pdb

 17%|█▋        | 164/961 [00:17<00:59, 13.49it/s]

LT00286.pdb
LT01196.pdb
LT00066.pdb
LT01198.pdb
LT01201.pdb
LT01207.pdb

 18%|█▊        | 170/961 [00:17<00:43, 18.07it/s]

LT01208.pdb
LT00009.pdb
LT00068.pdb
LT00379.pdb
LT01213.pdb
LT00067.pdb

 18%|█▊        | 174/961 [00:17<00:44, 17.51it/s]

LT00328.pdb
LT00529.pdb

 19%|█▊        | 179/961 [00:18<00:50, 15.47it/s]

LT01025.pdb
LT01218.pdb
LT01209.pdb
LT01219.pdb
LT00178.pdb
LT00219.pdb
LT01224.pdb
LT00187.pdb

 19%|█▉        | 183/961 [00:18<01:20,  9.63it/s]

LT02222.pdb
LT01225.pdb

 20%|█▉        | 188/961 [00:19<01:08, 11.27it/s]

LT01542.pdb
LT00011.pdb
LT00694.pdb
LT01228.pdb

 20%|█▉        | 190/961 [00:19<01:11, 10.74it/s]

LT00233.pdb
LT00185.pdb
LT00532.pdb

 20%|██        | 194/961 [00:19<00:54, 14.14it/s]

LT01231.pdb
LT01023.pdb
LT00341.pdb
LT00248.pdb
LT01235.pdb

 20%|██        | 197/961 [00:19<00:50, 15.12it/s]

LT00287.pdb
LT03578.pdb

 21%|██        | 199/961 [00:20<01:19,  9.55it/s]

LT03613.pdb

 21%|██        | 201/961 [00:20<01:45,  7.17it/s]

LT01269.pdb

 21%|██        | 203/961 [00:20<01:29,  8.44it/s]

LT00076.pdb
LT00881.pdb
LT00077.pdb

 21%|██▏       | 205/961 [00:47<43:13,  3.43s/it]

LT00734.pdb
LT02436.pdb

 22%|██▏       | 207/961 [00:47<28:44,  2.29s/it]

LT02430.pdb
LT02004.pdb
LT00361.pdb
LT02002.pdb

[21:04:32] UFFTYPER: Unrecognized atom type: Cu6+1 (1)
[21:04:36] UFFTYPER: Unrecognized atom type: Co3+3 (0)
 22%|██▏       | 213/961 [00:51<14:49,  1.19s/it]

LT01249.pdb
LT01250.pdb
LT00013.pdb
LT01253.pdb
LT00380.pdb

 22%|██▏       | 215/961 [00:54<16:05,  1.29s/it]

LT01255.pdb
LT01256.pdb
LT02345.pdb

 23%|██▎       | 218/961 [00:54<10:40,  1.16it/s]

LT02904.pdb
LT03652.pdb

 23%|██▎       | 222/961 [00:55<06:14,  1.97it/s]

LT03653.pdb
LT00539.pdb
LT00080.pdb
LT02891.pdb

 24%|██▎       | 226/961 [00:55<03:37,  3.38it/s]

LT00289.pdb
LT01188.pdb
LT03654.pdb
LT01243.pdb

 24%|██▍       | 230/961 [00:55<02:25,  5.02it/s]

LT01248.pdb
LT00563.pdb
LT00541.pdb
LT02726.pdb

 24%|██▍       | 234/961 [00:56<01:40,  7.22it/s]

LT00996.pdb
LT00081.pdb
LT03657.pdb

 25%|██▍       | 238/961 [00:56<01:26,  8.38it/s]

LT01265.pdb
LT01085.pdb
LT00573.pdb

 25%|██▍       | 240/961 [00:56<01:21,  8.88it/s]

LT03658.pdb
LT00082.pdb

 25%|██▌       | 242/961 [00:56<01:08, 10.45it/s]

LT00810.pdb
LT00682.pdb
LT01266.pdb
LT02909.pdb
LT01972.pdb

 26%|██▌       | 249/961 [00:57<00:40, 17.62it/s]

LT00870.pdb
LT02056.pdb
LT00327.pdb
LT00230.pdb
LT00865.pdb
LT00802.pdb
LT00084.pdb
LT02041.pdb

 26%|██▋       | 253/961 [00:57<00:34, 20.25it/s]

LT00737.pdb
LT01285.pdb
LT00806.pdb
LT03659.pdb

 27%|██▋       | 257/961 [00:57<00:51, 13.56it/s]

LT00085.pdb
LT00292.pdb

 27%|██▋       | 261/961 [00:58<01:21,  8.63it/s]

LT01292.pdb
LT00545.pdb
LT02877.pdb
LT00087.pdb
LT01623.pdb

 28%|██▊       | 266/961 [00:58<01:02, 11.09it/s]

LT00294.pdb
LT03660.pdb
LT01302.pdb

 28%|██▊       | 270/961 [00:59<00:54, 12.60it/s]

LT00295.pdb
LT00684.pdb
LT01040.pdb
LT00986.pdb

 29%|██▊       | 274/961 [00:59<00:49, 13.92it/s]

LT02905.pdb
LT00052.pdb
LT03661.pdb

 29%|██▊       | 276/961 [00:59<00:48, 14.08it/s]

LT01313.pdb
LT01314.pdb
LT00464.pdb

 29%|██▉       | 278/961 [01:00<01:13,  9.27it/s]

LT00393.pdb
LT00727.pdb
LT00909.pdb

 29%|██▉       | 282/961 [01:00<00:59, 11.33it/s]

LT00671.pdb
LT01318.pdb
LT01788.pdb
LT02035.pdb
LT01112.pdb

 30%|██▉       | 287/961 [01:00<01:00, 11.18it/s]

LT03662.pdb
LT00740.pdb
LT01849.pdb
LT03664.pdb

 30%|███       | 291/961 [01:01<01:08,  9.85it/s]

LT01323.pdb
LT03665.pdb
LT02024.pdb
LT03666.pdb

 31%|███       | 294/961 [01:01<01:22,  8.11it/s]

LT00663.pdb
LT03605.pdb

 31%|███       | 296/961 [01:02<01:27,  7.64it/s]

LT03667.pdb
LT00515.pdb
LT00296.pdb

 31%|███       | 300/961 [01:02<01:08,  9.66it/s]

LT03668.pdb
LT03669.pdb
LT01968.pdb
LT00538.pdb
LT03670.pdb

 32%|███▏      | 305/961 [01:02<00:56, 11.65it/s]

LT02444.pdb
LT01666.pdb
LT01149.pdb

 32%|███▏      | 307/961 [01:03<01:10,  9.31it/s]

LT01001.pdb
LT03672.pdb

 32%|███▏      | 309/961 [01:03<01:22,  7.90it/s]

LT00194.pdb

 32%|███▏      | 311/961 [01:03<01:09,  9.35it/s]

LT01214.pdb
LT03673.pdb
LT00092.pdb

 33%|███▎      | 315/961 [01:04<01:47,  5.99it/s]

LT02929.pdb
LT02881.pdb
LT01589.pdb

 33%|███▎      | 317/961 [01:04<01:30,  7.11it/s]

LT01334.pdb
LT00016.pdb
LT01342.pdb

 33%|███▎      | 321/961 [01:05<01:12,  8.81it/s]

LT02424.pdb
LT02043.pdb
LT00677.pdb

 34%|███▎      | 323/961 [01:05<01:03, 10.03it/s]

LT01161.pdb
LT01344.pdb
LT01345.pdb
LT00926.pdb

 34%|███▍      | 330/961 [01:05<00:34, 18.28it/s]

LT01348.pdb
LT00831.pdb
LT00795.pdb
LT01355.pdb
LT00240.pdb
LT01193.pdb
LT00653.pdb
LT01267.pdb

 35%|███▍      | 336/961 [01:06<01:18,  7.92it/s]

LT00394.pdb
LT01359.pdb
LT01153.pdb
LT01870.pdb

 35%|███▌      | 340/961 [01:06<01:00, 10.27it/s]

LT00270.pdb
LT00095.pdb
LT00554.pdb
LT03676.pdb

 36%|███▌      | 346/961 [01:07<00:40, 15.20it/s]

LT00097.pdb
LT00397.pdb
LT01846.pdb
LT00098.pdb
LT00670.pdb

[21:04:52] UFFTYPER: Unrecognized atom type: Ca+2 (0)
[21:04:52] UFFTYPER: Unrecognized atom type: Fe2+2 (0)

LT00099.pdb
LT03677.pdb
LT00590.pdb

 37%|███▋      | 351/961 [01:07<00:40, 15.20it/s]

LT03678.pdb
LT01370.pdb
LT01371.pdb
LT02357.pdb

 37%|███▋      | 353/961 [01:08<01:49,  5.55it/s]

LT00701.pdb

 37%|███▋      | 355/961 [01:09<01:52,  5.40it/s]

LT00167.pdb

 37%|███▋      | 357/961 [01:09<01:32,  6.54it/s]

LT03679.pdb
LT02342.pdb
LT01372.pdb

 38%|███▊      | 361/961 [01:09<01:06,  8.97it/s]

LT00857.pdb
LT01375.pdb
LT03680.pdb

 38%|███▊      | 364/961 [01:09<00:54, 11.04it/s]

LT00179.pdb
LT01381.pdb
LT00399.pdb
LT00018.pdb
LT02031.pdb

 38%|███▊      | 368/961 [01:09<00:46, 12.71it/s]

LT00400.pdb
LT01394.pdb
LT00298.pdb
LT00101.pdb
LT00172.pdb

 39%|███▉      | 373/961 [01:10<00:44, 13.32it/s]

LT01396.pdb
LT01580.pdb
LT00494.pdb
LT01125.pdb

 39%|███▉      | 375/961 [01:11<01:51,  5.24it/s][21:04:56] UFFTYPER: Unrecognized atom type: Ca+2 (0)
 39%|███▉      | 377/961 [01:11<01:37,  5.98it/s]

LT01194.pdb
LT03681.pdb
LT01398.pdb
LT01399.pdb

 40%|███▉      | 380/961 [01:11<01:33,  6.23it/s]

LT03682.pdb
LT03683.pdb

 40%|████      | 385/961 [01:12<00:55, 10.33it/s]

LT01054.pdb
LT00299.pdb
LT00300.pdb
LT03684.pdb
LT01086.pdb
LT00402.pdb

 40%|████      | 388/961 [01:12<00:44, 12.85it/s]

LT00020.pdb
LT01084.pdb
LT03685.pdb

 41%|████      | 392/961 [01:13<01:08,  8.33it/s]

LT02092.pdb
LT03687.pdb
LT00173.pdb

 41%|████      | 394/961 [01:13<01:07,  8.35it/s]

LT00243.pdb
LT00302.pdb

 42%|████▏     | 400/961 [01:13<00:44, 12.67it/s]

LT00836.pdb
LT00557.pdb
LT00558.pdb
LT01100.pdb
LT00829.pdb

 42%|████▏     | 405/961 [01:13<00:32, 17.26it/s]

LT01422.pdb
LT00708.pdb
LT00559.pdb
LT01433.pdb
LT00188.pdb
LT00814.pdb
LT00919.pdb
LT02026.pdb

 42%|████▏     | 408/961 [01:13<00:29, 19.00it/s]

LT00106.pdb
LT01437.pdb
LT01156.pdb
LT03689.pdb

 43%|████▎     | 414/961 [01:14<00:56,  9.62it/s]

LT02898.pdb
LT00560.pdb
LT00199.pdb
LT03610.pdb

 43%|████▎     | 416/961 [01:15<00:50, 10.82it/s]

LT00654.pdb
LT00107.pdb

 44%|████▎     | 420/961 [01:15<00:47, 11.37it/s]

LT00108.pdb
LT01444.pdb
LT01446.pdb

 44%|████▍     | 424/961 [01:15<00:54,  9.94it/s]

LT00022.pdb
LT03692.pdb
LT00109.pdb
LT01005.pdb
LT03694.pdb

 45%|████▍     | 432/961 [01:16<00:36, 14.49it/s]

LT00696.pdb
LT01469.pdb
LT00306.pdb
LT00818.pdb
LT00340.pdb
LT00234.pdb
LT02089.pdb
LT01475.pdb

 45%|████▌     | 435/961 [01:16<00:36, 14.26it/s]

LT03695.pdb
LT00182.pdb

 45%|████▌     | 437/961 [01:17<00:50, 10.45it/s]

LT02665.pdb
LT02431.pdb
LT00568.pdb

 46%|████▌     | 439/961 [01:18<02:13,  3.91it/s]

LT03696.pdb
LT03697.pdb

 46%|████▌     | 443/961 [01:19<01:38,  5.26it/s]

LT00111.pdb
LT00023.pdb

 46%|████▋     | 446/961 [01:19<01:12,  7.13it/s]

LT00204.pdb
LT00112.pdb
LT00660.pdb
LT02745.pdb

 47%|████▋     | 448/961 [01:19<01:03,  8.05it/s]

LT00886.pdb
LT00569.pdb
LT01481.pdb
LT00307.pdb
LT00493.pdb
LT02204.pdb

[21:05:05] UFFTYPER: Unrecognized charge state for atom: 0
[21:05:05] UFFTYPER: Unrecognized atom type: La+3 (0)
[21:05:05] UFFTYPER: Unrecognized charge state for atom: 0
[21:05:05] UFFTYPER: Unrecognized atom type: La+3 (0)
 47%|████▋     | 453/961 [01:19<00:47, 10.72it/s]

LT03698.pdb
LT03699.pdb

 47%|████▋     | 455/961 [01:19<00:54,  9.22it/s]

LT00933.pdb
LT03852.pdb

 48%|████▊     | 459/961 [01:20<00:54,  9.26it/s]

LT00113.pdb
LT03700.pdb
LT01238.pdb
LT03616.pdb

 48%|████▊     | 463/961 [01:20<00:50,  9.89it/s]

LT03701.pdb
LT00572.pdb

[21:05:06] UFFTYPER: Unrecognized atom type: Ca+2 (0)
 48%|████▊     | 465/961 [01:21<00:50,  9.77it/s]

LT02192.pdb
LT03702.pdb

 49%|████▉     | 469/961 [01:21<00:36, 13.30it/s]

LT01059.pdb
LT01486.pdb
LT00600.pdb
LT01488.pdb
LT02442.pdb

[21:05:06] UFFTYPER: Unrecognized atom type: Ca+2 (0)
 49%|████▉     | 473/961 [01:21<00:36, 13.47it/s]

LT01489.pdb
LT00752.pdb
LT01072.pdb
LT00482.pdb
LT02412.pdb

 50%|████▉     | 477/961 [01:23<01:52,  4.29it/s]

LT02445.pdb
LT01491.pdb

 50%|████▉     | 479/961 [01:23<01:27,  5.51it/s]

LT01077.pdb
LT00783.pdb
LT00571.pdb
LT01492.pdb

 50%|█████     | 481/961 [01:23<01:17,  6.21it/s]

LT01776.pdb
LT00574.pdb
LT02398.pdb

 50%|█████     | 484/961 [01:24<01:05,  7.28it/s]

LT00575.pdb
LT03703.pdb

 51%|█████     | 488/961 [01:24<00:54,  8.70it/s]

LT02087.pdb
LT01497.pdb
LT01498.pdb

 51%|█████     | 492/961 [01:24<00:46, 10.16it/s]

LT00181.pdb
LT03704.pdb
LT01499.pdb
LT00576.pdb
LT01501.pdb

 51%|█████▏    | 494/961 [01:24<00:48,  9.58it/s]

LT01240.pdb
LT03706.pdb

 52%|█████▏    | 496/961 [01:25<00:52,  8.91it/s]

LT00686.pdb
LT02411.pdb

 52%|█████▏    | 499/961 [01:25<01:00,  7.67it/s]

LT03708.pdb

 52%|█████▏    | 500/961 [01:25<01:03,  7.25it/s]

LT03709.pdb
LT02451.pdb

 52%|█████▏    | 502/961 [01:25<00:48,  9.41it/s]

LT00024.pdb
LT01503.pdb
LT03710.pdb

 52%|█████▏    | 504/961 [01:26<01:25,  5.35it/s]

LT00640.pdb

 53%|█████▎    | 508/961 [01:27<00:58,  7.74it/s]

LT03558.pdb
LT01508.pdb
LT00308.pdb
LT00781.pdb
LT00792.pdb
LT01511.pdb
LT01513.pdb

 53%|█████▎    | 512/961 [01:27<00:43, 10.27it/s]

LT00116.pdb
LT01514.pdb
LT00220.pdb

 54%|█████▍    | 518/961 [01:27<00:31, 13.87it/s]

LT00117.pdb
LT01908.pdb
LT02110.pdb
LT00790.pdb
LT00713.pdb
LT01520.pdb

 55%|█████▍    | 525/961 [01:27<00:22, 19.29it/s]

LT01521.pdb
LT00003.pdb
LT00414.pdb
LT01527.pdb
LT02086.pdb

 55%|█████▌    | 532/961 [01:28<00:19, 22.23it/s]

LT00841.pdb
LT00119.pdb
LT00723.pdb
LT00716.pdb
LT01532.pdb
LT00322.pdb

 56%|█████▌    | 536/961 [01:28<00:17, 24.28it/s]

LT00580.pdb
LT01468.pdb
LT00581.pdb
LT00026.pdb
LT01537.pdb
LT01547.pdb

 56%|█████▋    | 542/961 [01:28<00:20, 20.80it/s]

LT00787.pdb
LT00833.pdb
LT00121.pdb
LT02074.pdb
LT01545.pdb
LT00478.pdb
LT00222.pdb

 57%|█████▋    | 547/961 [01:28<00:24, 16.95it/s]

LT02072.pdb
LT01549.pdb
LT02046.pdb
LT00946.pdb

 57%|█████▋    | 551/961 [01:29<00:27, 14.79it/s]

LT00309.pdb
LT00584.pdb
LT00838.pdb
LT00895.pdb
LT01553.pdb
LT01557.pdb

 58%|█████▊    | 557/961 [01:29<00:21, 18.57it/s]

LT01558.pdb
LT03751.pdb
LT00184.pdb

 58%|█████▊    | 562/961 [01:29<00:21, 18.15it/s]

LT03712.pdb
LT00992.pdb
LT01126.pdb
LT01263.pdb
LT02956.pdb

 59%|█████▉    | 566/961 [01:30<00:25, 15.22it/s]

LT00416.pdb
LT02388.pdb
LT01560.pdb
LT00922.pdb

 59%|█████▉    | 568/961 [01:30<00:26, 15.09it/s]

LT01564.pdb
LT03713.pdb
LT00589.pdb

 59%|█████▉    | 570/961 [01:30<00:31, 12.60it/s]

LT01567.pdb
LT03714.pdb
LT02007.pdb

 60%|█████▉    | 575/961 [01:30<00:30, 12.50it/s]

LT01571.pdb
LT00905.pdb
LT03715.pdb

 60%|██████    | 579/961 [01:31<00:40,  9.42it/s]

LT02008.pdb
LT01574.pdb
LT01288.pdb

 60%|██████    | 581/961 [01:31<00:37, 10.08it/s]

LT00310.pdb
LT00910.pdb
LT01581.pdb
LT01582.pdb

 61%|██████    | 583/961 [01:31<00:32, 11.56it/s]

LT03716.pdb

 61%|██████    | 585/961 [01:32<00:40,  9.31it/s]

LT01587.pdb
LT01588.pdb
LT03717.pdb

 61%|██████▏   | 589/961 [01:33<01:00,  6.16it/s]

LT00311.pdb
LT00593.pdb
LT01007.pdb
LT00594.pdb

 61%|██████▏   | 591/961 [01:33<00:48,  7.67it/s]

LT01212.pdb
LT00124.pdb
LT01012.pdb

 62%|██████▏   | 594/961 [01:33<00:44,  8.28it/s]

LT00595.pdb

 62%|██████▏   | 596/961 [01:34<00:57,  6.33it/s]

LT03582.pdb
LT00260.pdb
LT00312.pdb

 62%|██████▏   | 600/961 [01:34<00:39,  9.22it/s]

LT01594.pdb
LT01595.pdb
LT00313.pdb
LT02164.pdb

 63%|██████▎   | 606/961 [01:34<00:27, 13.10it/s]

LT00607.pdb
LT01600.pdb
LT00314.pdb
LT01601.pdb
LT03718.pdb
LT01602.pdb

 63%|██████▎   | 610/961 [01:34<00:30, 11.55it/s]

LT03719.pdb
LT00217.pdb

 64%|██████▍   | 614/961 [01:35<00:21, 16.34it/s]

LT01184.pdb
LT01092.pdb
LT01854.pdb
LT00125.pdb
LT01608.pdb
LT00315.pdb
LT01611.pdb
LT00211.pdb

 65%|██████▍   | 621/961 [01:35<00:19, 17.43it/s]

LT02269.pdb
LT01614.pdb
LT01615.pdb
LT00602.pdb
LT03603.pdb

 65%|██████▍   | 623/961 [01:36<01:07,  4.99it/s]

LT03721.pdb

 65%|██████▌   | 625/961 [01:37<01:12,  4.64it/s]

LT01620.pdb
LT00259.pdb
LT03722.pdb

 65%|██████▌   | 629/961 [01:37<00:54,  6.04it/s]

LT01102.pdb
LT00126.pdb
LT02145.pdb
LT03896.pdb

 66%|██████▌   | 634/961 [01:38<00:45,  7.25it/s]

LT00206.pdb
LT01619.pdb
LT03725.pdb
LT02216.pdb

 66%|██████▋   | 638/961 [01:38<00:39,  8.28it/s]

LT02085.pdb
LT02210.pdb
LT03726.pdb
LT03727.pdb

 67%|██████▋   | 640/961 [01:39<00:42,  7.54it/s]

LT02880.pdb
LT00845.pdb

 67%|██████▋   | 645/961 [01:39<00:28, 11.23it/s]

LT00429.pdb
LT00847.pdb
LT01056.pdb
LT02084.pdb
LT00979.pdb
LT00235.pdb

 68%|██████▊   | 650/961 [01:39<00:24, 12.79it/s]

LT00808.pdb
LT00690.pdb
LT00605.pdb

 68%|██████▊   | 652/961 [01:40<00:25, 12.34it/s]

LT03728.pdb
LT03594.pdb
LT01252.pdb

 68%|██████▊   | 656/961 [01:40<00:22, 13.38it/s]

LT01130.pdb
LT02055.pdb
LT03565.pdb
LT00606.pdb
LT01637.pdb
LT01015.pdb

 69%|██████▊   | 659/961 [01:40<00:25, 11.83it/s]

LT02061.pdb

 69%|██████▉   | 661/961 [01:41<00:38,  7.73it/s]

LT00128.pdb
LT00672.pdb
LT03733.pdb

 69%|██████▉   | 663/961 [01:41<00:35,  8.36it/s]

LT00246.pdb
LT01644.pdb

 70%|██████▉   | 668/961 [01:41<00:27, 10.71it/s]

LT00488.pdb
LT01648.pdb
LT00130.pdb
LT01652.pdb
LT02446.pdb

 70%|██████▉   | 672/961 [01:42<00:25, 11.47it/s]

LT00216.pdb
LT00131.pdb
LT00955.pdb
LT01655.pdb

 70%|███████   | 677/961 [01:42<00:22, 12.85it/s]

LT03735.pdb
LT00826.pdb
LT01657.pdb
LT00030.pdb
LT02082.pdb
LT00703.pdb

 71%|███████   | 681/961 [01:42<00:16, 17.18it/s]

LT00032.pdb
LT00780.pdb
LT01671.pdb
LT03736.pdb

 71%|███████▏  | 686/961 [01:43<00:29,  9.28it/s]

LT01672.pdb
LT01673.pdb

 72%|███████▏  | 688/961 [01:43<00:25, 10.62it/s]

LT00134.pdb
LT00697.pdb
LT03550.pdb
LT01679.pdb
LT01680.pdb
LT00668.pdb

[21:05:29] UFFTYPER: Unrecognized atom type: Ca+2 (0)
 72%|███████▏  | 692/961 [01:43<00:23, 11.34it/s]

LT03737.pdb
LT00486.pdb

 72%|███████▏  | 696/961 [01:44<00:26, 10.00it/s]

LT02883.pdb
LT02434.pdb
LT03740.pdb

 73%|███████▎  | 698/961 [01:44<00:24, 10.95it/s]

LT00610.pdb
LT00698.pdb
LT03741.pdb

 73%|███████▎  | 700/961 [01:44<00:32,  8.06it/s]

LT00492.pdb

 73%|███████▎  | 702/961 [02:00<09:55,  2.30s/it]

LT00665.pdb
LT00186.pdb

 73%|███████▎  | 705/961 [02:01<05:45,  1.35s/it]

LT00225.pdb
LT00435.pdb
LT00612.pdb

 74%|███████▎  | 707/961 [02:01<04:03,  1.04it/s]

LT00180.pdb
LT01154.pdb
LT03742.pdb
LT00613.pdb

 74%|███████▍  | 714/961 [02:01<01:25,  2.88it/s]

LT00261.pdb
LT01698.pdb
LT01699.pdb
LT00614.pdb
LT00437.pdb

 75%|███████▍  | 717/961 [02:01<01:05,  3.70it/s]

LT02219.pdb
LT00192.pdb
LT00205.pdb

 75%|███████▍  | 720/961 [02:02<00:47,  5.06it/s]

LT01705.pdb
LT01708.pdb
LT00083.pdb
LT01706.pdb
LT00349.pdb

 75%|███████▌  | 725/961 [02:02<00:32,  7.19it/s]

LT00848.pdb
LT03197.pdb
LT00137.pdb
LT01713.pdb

 76%|███████▌  | 732/961 [02:02<00:17, 13.02it/s]

LT00166.pdb
LT02081.pdb
LT01980.pdb
LT01716.pdb
LT01721.pdb
LT00267.pdb
LT01723.pdb
LT01725.pdb

 76%|███████▋  | 735/961 [02:03<00:28,  8.01it/s]

LT01923.pdb

 77%|███████▋  | 737/961 [02:03<00:32,  6.92it/s]

LT00264.pdb
LT00183.pdb
LT00642.pdb

 77%|███████▋  | 739/961 [02:04<00:28,  7.69it/s]

LT01217.pdb
LT01726.pdb

 77%|███████▋  | 741/961 [02:04<00:27,  8.06it/s]

LT00138.pdb
LT01192.pdb

 78%|███████▊  | 745/961 [02:04<00:22,  9.65it/s]

LT01204.pdb
LT02433.pdb
LT03743.pdb
LT01002.pdb

 78%|███████▊  | 747/961 [02:05<00:28,  7.57it/s]

LT01729.pdb

 78%|███████▊  | 750/961 [02:05<00:30,  7.01it/s]

LT01730.pdb
LT03606.pdb
LT01479.pdb

 78%|███████▊  | 751/961 [02:05<00:28,  7.36it/s]

LT00139.pdb

 78%|███████▊  | 752/961 [02:06<00:50,  4.15it/s]

LT00034.pdb

 78%|███████▊  | 753/961 [02:07<01:36,  2.16it/s]

LT03745.pdb

 78%|███████▊  | 754/961 [02:07<01:38,  2.10it/s]

LT01057.pdb

 79%|███████▊  | 755/961 [02:08<01:53,  1.81it/s]

LT01128.pdb

 79%|███████▊  | 756/961 [02:09<01:53,  1.81it/s]

LT02352.pdb
LT01731.pdb
LT00937.pdb
LT03746.pdb

 79%|███████▉  | 762/961 [02:09<00:46,  4.31it/s]

LT02894.pdb
LT03747.pdb
LT03748.pdb

 80%|███████▉  | 764/961 [02:10<00:35,  5.61it/s]

LT01020.pdb
LT01735.pdb
LT01737.pdb

 80%|███████▉  | 768/961 [02:10<00:33,  5.71it/s]

LT02390.pdb
LT01016.pdb
LT01026.pdb

 80%|████████  | 770/961 [02:10<00:27,  6.99it/s]

LT00619.pdb
LT03749.pdb
LT00990.pdb
LT00140.pdb

 80%|████████  | 773/961 [02:11<00:20,  9.14it/s][21:05:56] UFFTYPER: Unrecognized atom type: Ca+2 (0)

LT01928.pdb

 81%|████████  | 775/961 [02:11<00:25,  7.18it/s]

LT03750.pdb
LT00564.pdb
LT02441.pdb
LT03752.pdb

 81%|████████  | 778/961 [02:11<00:19,  9.27it/s]

LT01684.pdb
LT01262.pdb
LT01746.pdb

 81%|████████▏ | 783/961 [02:12<00:23,  7.63it/s]

LT03753.pdb
LT00667.pdb
LT01974.pdb

 82%|████████▏ | 785/961 [02:12<00:20,  8.51it/s][21:05:58] UFFTYPER: Unrecognized charge state for atom: 1

LT03143.pdb
LT00624.pdb
LT01749.pdb
LT03754.pdb
LT03755.pdb

 82%|████████▏ | 791/961 [02:13<00:15, 11.04it/s]

LT03756.pdb
LT03757.pdb

 83%|████████▎ | 793/961 [02:13<00:13, 12.37it/s]

LT03758.pdb
LT00625.pdb
LT01039.pdb
LT00988.pdb
LT01033.pdb

 83%|████████▎ | 796/961 [02:13<00:12, 13.66it/s]

LT00656.pdb
LT00142.pdb

 83%|████████▎ | 798/961 [02:13<00:15, 10.64it/s]

LT03761.pdb
LT00443.pdb

 83%|████████▎ | 802/961 [02:15<00:31,  5.07it/s][21:06:00] UFFTYPER: Unrecognized atom type: Zr (0)

LT01251.pdb
LT02449.pdb
LT02337.pdb
LT00480.pdb
LT02343.pdb
LT03762.pdb
LT02901.pdb

 84%|████████▍ | 809/961 [02:15<00:16,  8.95it/s]

LT01191.pdb
LT03763.pdb
LT03764.pdb

 84%|████████▍ | 811/961 [02:15<00:17,  8.81it/s]

LT01241.pdb
LT02010.pdb
LT00627.pdb
LT03765.pdb

 85%|████████▍ | 816/961 [02:16<00:14,  9.67it/s]

LT00143.pdb
LT00144.pdb

 85%|████████▌ | 819/961 [02:16<00:11, 11.85it/s]

LT02728.pdb
LT01766.pdb
LT01816.pdb
LT00699.pdb
LT00146.pdb
LT01933.pdb

 86%|████████▌ | 823/961 [02:16<00:09, 14.91it/s]

LT00147.pdb
LT00632.pdb
LT00148.pdb
LT01779.pdb

 86%|████████▌ | 826/961 [02:16<00:08, 16.27it/s]

LT00565.pdb
LT03766.pdb

 86%|████████▌ | 828/961 [02:16<00:09, 13.39it/s]

LT00448.pdb

 86%|████████▋ | 830/961 [02:17<00:19,  6.77it/s]

LT01129.pdb
LT03576.pdb

 87%|████████▋ | 832/961 [02:17<00:18,  7.04it/s]

LT03898.pdb
LT03768.pdb

 87%|████████▋ | 834/961 [02:18<00:16,  7.53it/s]

LT00152.pdb
LT00982.pdb
LT00664.pdb

 87%|████████▋ | 838/961 [02:18<00:12, 10.16it/s]

LT02884.pdb
LT00687.pdb
LT03769.pdb

 87%|████████▋ | 840/961 [02:18<00:12,  9.91it/s]

LT03770.pdb
LT00485.pdb
LT00577.pdb
LT01944.pdb

 88%|████████▊ | 844/961 [02:19<00:22,  5.32it/s]

LT02063.pdb
LT03772.pdb

 88%|████████▊ | 845/961 [02:19<00:21,  5.35it/s]

LT01785.pdb
LT00153.pdb
LT03773.pdb

 88%|████████▊ | 849/961 [02:21<00:28,  3.94it/s]

LT02224.pdb

 88%|████████▊ | 850/961 [02:21<00:24,  4.46it/s]

LT03775.pdb
LT01787.pdb
LT00634.pdb
LT00877.pdb

 89%|████████▉ | 853/961 [02:21<00:15,  6.95it/s]

LT02397.pdb
LT01858.pdb

 89%|████████▉ | 858/961 [02:22<00:13,  7.92it/s]

LT01239.pdb
LT00450.pdb
LT00154.pdb
LT00635.pdb
LT01981.pdb
LT00452.pdb
LT00451.pdb
LT01805.pdb

 90%|████████▉ | 863/961 [02:22<00:08, 11.76it/s]

LT00989.pdb
LT02413.pdb

 91%|█████████ | 870/961 [02:22<00:05, 15.96it/s]

LT00227.pdb
LT00636.pdb
LT00691.pdb
LT00998.pdb
LT01815.pdb
LT00637.pdb
LT01818.pdb
LT01220.pdb

 91%|█████████ | 876/961 [02:23<00:05, 15.52it/s]

LT03776.pdb
LT00155.pdb
LT02392.pdb
LT00266.pdb

 92%|█████████▏| 882/961 [02:23<00:04, 18.41it/s]

LT00453.pdb
LT00156.pdb
LT01820.pdb
LT01822.pdb
LT01011.pdb
LT00661.pdb
LT00455.pdb
LT00158.pdb

 92%|█████████▏| 888/961 [02:23<00:04, 15.85it/s]

LT00639.pdb
LT01827.pdb
LT02903.pdb

 93%|█████████▎| 890/961 [02:24<00:04, 14.81it/s]

LT01828.pdb
LT00923.pdb
LT01829.pdb

 93%|█████████▎| 893/961 [02:24<00:04, 14.62it/s]

LT01830.pdb
LT00338.pdb
LT00700.pdb

 93%|█████████▎| 895/961 [02:24<00:05, 13.08it/s]

LT01833.pdb
LT01834.pdb
LT03076.pdb
LT00375.pdb
LT00457.pdb
LT03777.pdb

 94%|█████████▍| 904/961 [02:24<00:03, 18.45it/s]

LT01839.pdb
LT01840.pdb
LT01841.pdb
LT01842.pdb
LT01844.pdb
LT00798.pdb

 94%|█████████▍| 907/961 [02:25<00:03, 17.75it/s]

LT00168.pdb
LT00213.pdb
LT00516.pdb

 95%|█████████▍| 909/961 [02:25<00:03, 17.21it/s]

LT00645.pdb
LT03779.pdb

 95%|█████████▌| 913/961 [02:25<00:03, 13.03it/s]

LT02356.pdb
LT03780.pdb
LT02443.pdb

 95%|█████████▌| 915/961 [02:25<00:04,  9.46it/s]

LT03781.pdb
LT03782.pdb

 95%|█████████▌| 917/961 [02:26<00:04,  9.70it/s]

LT03783.pdb
LT03784.pdb
LT01855.pdb

 96%|█████████▌| 919/961 [02:26<00:04,  9.80it/s]

LT01856.pdb
LT03785.pdb

 96%|█████████▋| 925/961 [02:26<00:02, 12.53it/s]

LT01971.pdb
LT01109.pdb
LT00160.pdb
LT01857.pdb

 96%|█████████▋| 927/961 [02:26<00:02, 12.88it/s]

LT02389.pdb
LT01135.pdb
LT01242.pdb
LT02435.pdb

 97%|█████████▋| 929/961 [02:27<00:02, 13.36it/s]

LT03786.pdb

 97%|█████████▋| 933/961 [02:27<00:02, 10.09it/s]

LT00174.pdb
LT00332.pdb
LT03787.pdb
LT03788.pdb

 97%|█████████▋| 935/961 [02:27<00:02, 10.78it/s]

LT00969.pdb
LT02391.pdb
LT01861.pdb
LT03789.pdb

 98%|█████████▊| 938/961 [03:31<03:04,  8.04s/it]

LT02410.pdb
LT00162.pdb

 98%|█████████▊| 940/961 [03:31<02:06,  6.00s/it]

LT02009.pdb
LT01516.pdb

 98%|█████████▊| 942/961 [03:31<01:23,  4.38s/it]

LT03563.pdb

 98%|█████████▊| 944/961 [03:34<00:55,  3.29s/it]

LT03790.pdb
LT01097.pdb
LT00462.pdb

 99%|█████████▉| 950/961 [03:34<00:12,  1.13s/it]

LT02902.pdb
LT03792.pdb
LT00647.pdb
LT01867.pdb
LT02033.pdb

 99%|█████████▉| 952/961 [03:34<00:07,  1.15it/s]

LT01869.pdb
LT00648.pdb
LT03600.pdb

100%|█████████▉| 958/961 [03:35<00:01,  2.63it/s]

LT00163.pdb
LT00649.pdb
LT01874.pdb
LT01017.pdb
LT01010.pdb
LT00164.pdb

100%|██████████| 961/961 [03:35<00:00,  4.46it/s]

LT00165.pdb

,LTKBID,COMPOUND_NAME,NAME,Way,SeverityClass,LabelSection,vDILI-Concern,Comment,CID,IUPAC_Name,SMILES,mol
0,LT00040,Abacavir sulfate,阿巴卡韦硫酸盐,口服,8,Warnings & precautions,vMOST-DILI-concern,Unchanged,441384,"bis([(1S,4R)-4-[2-amino-6-(cyclopropylamino)pu...",C1CC1NC2=C3C(=NC(=N2)N)N(C=N3)[C@@H]4C[C@@H](C...,<rdkit.Chem.rdchem.Mol object at 0x000001958E1...
1,LT03619,Abemaciclib,阿贝莫司他,口服,3,Warnings & precautions,vLess-DILI-concern,New,46220502,N-[5-[(4-ethylpiperazin-1-yl)methyl]-2-pyridin...,CCN1CCN(CC1)CC2=CN=C(C=C2)NC3=NC=C(C(=N3)C4=CC...,<rdkit.Chem.rdchem.Mol object at 0x000001958E1...
2,LT02339,Abiraterone acetate,阿比特龙醋酸盐,口服,8,Warnings & precautions,vMost-DILI-concern,New,9821849,"[(3S,8R,9S,10R,13S,14S)-10,13-dimethyl-17-pyri...",CC(=O)O[C@H]1CC[C@@]2([C@H]3CC[C@]4([C@H]([C@@...,<rdkit.Chem.rdchem.Mol object at 0x000001958E1...
3,LT03614,Acalabrutinib,阿卡布替尼,口服,4,Adverse reactions,Ambiguous-DILI-concern,New,71226662,4-[8-amino-3-[(2S)-1-but-2-ynoylpyrrolidin-2-y...,CC#CC(=O)N1CCC[C@H]1C2=NC(=C3N2C=CN=C3N)C4=CC=...,<rdkit.Chem.rdchem.Mol object at 0x000001958E1...
4,LT01141,Acamprosate calcium,阿坎酸钙,口服,3,Adverse reactions,vLess-DILI-concern,Unchanged,155434,calcium bis(3-acetamidopropane-1-sulfonate),CC(=O)NCCCS(=O)(=O)[O-].CC(=O)NCCCS(=O)(=O)[O-...,<rdkit.Chem.rdchem.Mol object at 0x000001958E1...

In [7]:
# 统计生成的pdb文件数量
pdbqtList = os.listdir()
pdbqtList = [i for i in pdbqtList if '.pdb' in i]
print(f'生成的pdb文件数量为{len(pdbqtList)}')

生成的pdb文件数量为958

In [8]:
#  创建文件夹
filenameList = os.listdir()
if "pdb2pdbqt" in filenameList:
    pass
else:
    os.mkdir("pdb2pdbqt")

In [38]:
#  分子转换
import time
# for filename in tqdm(filenameList):
#     if '.pdb' in filename:
#         filename = filename.replace('.pdb', '')
#         # print(os.getcwd())      
#         os.system(f"C:/ProgramData/MGLTools-1.5.7/python.exe C:/ProgramData/MGLTools-1.5.7/Lib/site-packages/AutoDockTools/Utilities24/prepare_ligand4.py -l {filename}.pdb -o ./pdb2pdbqt/{filename}.pdbqt -A hydrogens")

# 修改上方代码，一旦运行超过2min，跳过该分子，继续下一个分子，即限定每次循环不超过2min
import subprocess
for filename in tqdm(filenameList):
    if '.pdb' in filename:
        filename = filename.replace('.pdb', '')
        try:
            start = time.time()
            subprocess.Popen(f"C:/ProgramData/MGLTools-1.5.7/python.exe C:/ProgramData/MGLTools-1.5.7/Lib/site-packages/AutoDockTools/Utilities24/prepare_ligand4.py -l {filename}.pdb -o ./pdb2pdbqt/{filename}.pdbqt -A hydrogens")
            end = time.time()
            if end - start > 120:
                pass
        except:
            pass

100%|██████████| 982/982 [00:36<00:00, 26.58it/s]

In [39]:
# 统计pdb2pdbqt中生成的pdbqt文件数量
pdbqtList = os.listdir('pdb2pdbqt')
pdbqtList = [i for i in pdbqtList if '.pdbqt' in i]
print(f'生成的pdbqt文件数量为{len(pdbqtList)}')

生成的pdbqt文件数量为953

In [40]:
# 删除文件夹下.pdb文件
for file in os.listdir():
    if '.pdb' in file:
        os.remove(file)

In [41]:
# pdb2pdbqt文件夹改名为ligand
os.rename('pdb2pdbqt', 'DILI_ligands')